### ISSUE TITLE
npm run tauri dev時に、表示されるvrc-get-guiをアクティブにしないとエラーが出る?

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#678]
### Description of the bug / バグの説明

発生した場合の対症療法: 右クリックから再読み込みしたり、ホットリロードさせたりすると普通に動きます。

powershell側
```sh
    Finished dev [unoptimized + debuginfo] target(s) in 2m 33s
2024-03-29T16:06:09.626073+09:00 [DEBUG] vrc_get_vpm::io::tokio: initializing EnvironmentIo with config folder C:\Users\Sayamame\AppData\Local\VRChatCreatorCompanion
2024-03-29T16:06:09.629392+09:00 [ INFO] vrc_get_gui::logging: logging to file C:\Users\Sayamame\AppData\Local\VRChatCreatorCompanion\vrc-get-logs\vrc-get-2024-03-29_07-06-09.627112.log
 ○ Compiling /projects ...
2024-03-29T16:06:17.169758+09:00 [ INFO] vrc_get_gui::commands: reloading settings files
2024-03-29T16:06:17.188507+09:00 [ INFO] vrc_get_gui::commands: finished updating unity from unity hub
 ✓ Compiled /projects in 18.4s (1388 modules)
ReferenceError: navigator is not defined
    at isWindows (webpack-internal:///(ssr)/./node_modules/@tauri-apps/api/helpers/os-check.js:10:5)
    at eval (webpack-internal:///(ssr)/./node_modules/@tauri-apps/api/os.js:46:76)
    at (ssr)/./node_modules/@tauri-apps/api/os.js (E:\GitHub\vrc-get\vrc-get-gui\.next\server\vendor-chunks\@tauri-apps.js:60:1)
    at Function.__webpack_require__ (E:\GitHub\vrc-get\vrc-get-gui\.next\server\webpack-runtime.js:33:42)
    at async eval (webpack-internal:///(ssr)/./lib/os.ts:10:16)
ReferenceError: navigator is not defined
    at isWindows (webpack-internal:///(ssr)/./node_modules/@tauri-apps/api/helpers/os-check.js:10:5)
    at eval (webpack-internal:///(ssr)/./node_modules/@tauri-apps/api/os.js:46:76)
    at (ssr)/./node_modules/@tauri-apps/api/os.js (E:\GitHub\vrc-get\vrc-get-gui\.next\server\vendor-chunks\@tauri-apps.js:60:1)
    at Function.__webpack_require__ (E:\GitHub\vrc-get\vrc-get-gui\.next\server\webpack-runtime.js:33:42)
    at async eval (webpack-internal:///(ssr)/./lib/os.ts:10:16)
 ⨯ node_modules\@tauri-apps\api\helpers\os-check.js (6:0) @ isWindows
 ⨯ unhandledRejection: ReferenceError: navigator is not defined
    at isWindows (webpack-internal:///(ssr)/./node_modules/@tauri-apps/api/helpers/os-check.js:10:5)
    at eval (webpack-internal:///(ssr)/./node_modules/@tauri-apps/api/os.js:46:76)
    at (ssr)/./node_modules/@tauri-apps/api/os.js (E:\GitHub\vrc-get\vrc-get-gui\.next\server\vendor-chunks\@tauri-apps.js:60:1)
    at Function.__webpack_require__ (E:\GitHub\vrc-get\vrc-get-gui\.next\server\webpack-runtime.js:33:42)
    at async eval (webpack-internal:///(ssr)/./lib/os.ts:10:16)
null
 ⨯ node_modules\@tauri-apps\api\helpers\os-check.js (6:0) @ isWindows
 ⨯ unhandledRejection: ReferenceError: navigator is not defined
i/os.js:46:76)
    at (ssr)/./node_modules/@tauri-apps/api/os.js (E:\GitHub\vrc-get\vrc-get-gui\.next\server\vendor-chunks\@tauri-apps.js:60:1)
    at Function.__webpack_require__ (E:\GitHub\vrc-get\vrc-get-gui\.next\server\webpack-runtime.js:33:42)
    at async eval (webpack-internal:///(ssr)/./lib/os.ts:10:16)
null
 ✓ Compiled in 604ms (689 modules)
```
vrc-get-gui側
```js
Unhandled Runtime Error
ChunkLoadError: Loading chunk app/layout failed.
(timeout: http://localhost:3000/_next/static/chunks/app/layout.js)

Call Stack
__webpack_require__.f.j
file:///E:/GitHub/vrc-get/vrc-get-gui/.next/static/chunks/webpack.js (853:29)
<unknown>
file:///E:/GitHub/vrc-get/vrc-get-gui/.next/static/chunks/webpack.js (155:40)
Array.reduce
<anonymous>
__webpack_require__.e
file:///E:/GitHub/vrc-get/vrc-get-gui/.next/static/chunks/webpack.js (154:67)
fn.e
file:///E:/GitHub/vrc-get/vrc-get-gui/.next/static/chunks/webpack.js (391:50)
loadChunk
(app-pages-browser)\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (202:31)
preloadModule
(app-pages-browser)\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (128:0)
resolveModule
(app-pages-browser)\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (1756:0)
processFullRow
(app-pages-browser)\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (1827:0)
processBinaryChunk
(app-pages-browser)\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (1975:0)
progress
(app-pages-browser)\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.browser.development.js (2055:0)
```

### Steps to Reproduce / 再現手順

タイトル通り

### Expected Behavior / 想定される挙動

通常起動と同様に、アクティブにしていなくても自動的に読み込みが終わっていて欲しいはず

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

### Additional context / 補足

npm: 10.2.4 (もしかしてちょっと古い?)

**Comment by Spokeek** [comment]
I'm not sure i am able to reproduce that issue @Sayamame-beans . It's an old one but still.

I had to translate the issue and the context seems translated as vrc-get gui is not in "active" state. Can you clarify the issue you faced ?
